package com.home.test.runner;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import static org.junit.Assert.*;

import org.junit.AfterClass;

public class LibraryTest {
    private static WebDriver webDriver;
	@Test public void testSomeLibraryMethod() {
		webDriver.get("https://google.com");
    }
	@AfterClass
	public static void setDrt(){
		System.out.println("Test After Class");
	}
    public static void setDriver(WebDriver webDriver){
    	LibraryTest.webDriver=webDriver;
    	if(null==webDriver){
    		System.out.println("Inside Test1");
    	}
    }
}
