package com.home.test.runner;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.WebDriver;

public class LibraryTest2 {
    @Test public void testSomeLibraryMethod() {
    	
    }
    
    public static void setDriver(WebDriver webDriver){
    	if(null==webDriver){
    		System.out.println("Inside");
    	}
    }
}
