/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.openqa.selenium.WebDriver;

public class LibraryTest{
	private static WebDriver webDriver;
    @Test public void testSomeLibraryMethod() {
    	
    }
    public static void setDriver(WebDriver webDriver){
    	LibraryTest.webDriver=webDriver;
    }
}
